- name: remove the neovim package if installed
  become: "{{ ansible_facts['os_family'] != 'Darwin' }}"
  package:
    name: "neovim"
    state: absent

- name: remove neovim git dir if present
  become: true
  ansible.builtin.file:
    path: '/tmp/neovim'
    state: absent

- name: clone neovim
  become: false
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim.git
    dest: '/tmp/neovim'
    depth: 1
    version: stable

- name: install neovim deps on Debian
  become: true
  when: ansible_facts['os_family'] == "Debian"
  package:
    name:
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
      - build-essential
      - lua5.1
      - liblua5.1-0-dev
    state: latest

- name: install neovim deps on AL2
  become: true
  when: ansible_distribution == "Amazon"
  package:
    name:
      - ninja-build
      - gettext
      - make
      - gcc
      - unzip
      - curl
    state: latest

- name: install neovim deps on Mac
  when: ansible_facts['os_family'] == "Darwin"
  package:
    name:
      - ninja
      - gettext
      - curl
      - lua
    state: latest

- name: neovim -- make
  ansible.builtin.command: make CMAKE_BUILD_TYPE=Release
  args:
    chdir: "/tmp/neovim"

- name: neovim -- make install
  become: true
  ansible.builtin.command: make install
  args:
    chdir: "/tmp/neovim"
